[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py38']
exclude = '''

(
  /(
      \
    | migrations
  )/
)
'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
skip=['migrations']
