{{- if .Values.mariadb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ include "pdf_gen_poc.name" . }}-mariadb"
  labels:
    deployment: "{{ include "pdf_gen_poc.name" . }}-mariadb"
  namespace: {{ .Values.nameSpace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ include "pdf_gen_poc.name" . }}-mariadb"
  template:
    metadata:
      labels:
        app: "{{ include "pdf_gen_poc.name" . }}-mariadb"
    spec:
      containers:
        - name: "{{ include "pdf_gen_poc.name" . }}-mariadb"
          image: "{{ .Values.mariadb.repository }}:{{ .Values.mariadb.tag }}"
          env:
          {{- range $k, $v := .Values.mariadb.environment }}
            - name: {{ $k }}
              value: {{ $v | quote }}
          {{- end }}
{{- end }}
