{{- if .Values.ingress_restricted.enabled -}}
{{- $fullName := include "pdf_gen_poc.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pdf_gen_poc-ingress-restricted
  labels:
    app.kubernetes.io/name: {{ include "pdf_gen_poc.name" . }}
    helm.sh/chart: {{ include "pdf_gen_poc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress_restricted.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress_restricted.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 80
        {{- end }}
  {{- end }}
{{- end }}
