{{- if .Values.mariadb.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdf_gen_poc.fullname" . }}-mariadb
  namespace: {{ .Values.nameSpace }}
spec:
  ports:
  - port: {{ .Values.mariadb.service.port }}
  selector:
    app: pdf_gen_poc-mariadb
{{- end }}
