apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pdf_gen_poc.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.iam_role }}
  labels:
    app.kubernetes.io/name: {{ include "pdf_gen_poc.name" . }}
    helm.sh/chart: {{ include "pdf_gen_poc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
