apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdf_gen_poc.fullname" . }}
  labels:
   app.kubernetes.io/name: {{ include "pdf_gen_poc.name" . }}
   helm.sh/chart: {{ include "pdf_gen_poc.chart" . }}
   app.kubernetes.io/instance: {{ .Release.Name }}
   app.kubernetes.io/managed-by: {{ .Release.Service }}
  namespace: {{ .Values.nameSpace }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 8000
  selector:
    app: pdf_gen_poc-node
    app.kubernetes.io/name: {{ include "pdf_gen_poc.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
