replicaCount: 1

image:
  repository: 822523734328.dkr.ecr.eu-west-1.amazonaws.com/pdf_gen_poc
  tag: latest

nameOverride: ""
fullnameOverride: ""

nameSpace: "BRANCH_PLACEHOLDER-pdf_gen_poc"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations: ""
  tls: []
  hosts:
    - host: BRANCH_PLACEHOLDER.pdf_gen.dev.mobilevikings.be
      paths:
        - /

ingress_restricted:
  enabled: false
  annotations: ""
  hosts: ""
  tls: ""

memoryLimit:
  django: "1000Mi"
  celeryBeat: "150Mi"
  celeryWorker: "1000Mi"

memoryRequest:
  django: "500Mi"
  celeryBeat: "100Mi"
  celeryWorker: "1000Mi"

envSecrets:
  - "SENTRY_DSN"

environment:
  DEBUG: "True"
  ALLOWED_HOSTS: "*"
  DJANGO_CONFIG_CONTEXT: "dev"
  DJANGO_RUNTIME_CONTEXT: "uwsgi.pdf_gen_poc"
  DATABASE_URL: "mysql://root:dev@BRANCH_PLACEHOLDER-pdf_gen_poc-mariadb:3306/pdf_gen_poc?charset=utf8mb4"
  CACHE_URL: "redis://BRANCH_PLACEHOLDER-pdf_gen_poc-redis:6379/0"
  CELERY_BROKER_URL: "redis://BRANCH_PLACEHOLDER-pdf_gen_poc-redis:6379/0"

mariadb:
  enabled: true
  repository: mariadb
  tag: 10.4-bionic
  environment:
    MYSQL_ROOT_PASSWORD: "dev"
    MYSQL_DATABASE: "pdf_gen_poc"
  service:
    port: 3306

iam_role: "arn:aws:iam::083973106063:role/MV-ROLE-DEV-SA-{{ "pdf_gen_poc" | upper }}"

redis:
  enabled: true
  repository: redis
  tag: 5.0-buster
  service:
    port: 6379
